// Generates downloadable source code for a web or mobile app
// based on the components the user placed on the SENTINEL canvas.

export interface ExportNode {
  uid: string;
  name: string;
  itemId: string;
  label: string;
  hint: string;
}

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// Render a single canvas node to plain HTML markup.
function renderNode(node: ExportNode): string {
  const label = esc(node.name);
  switch (node.itemId) {
    case "button":
      return `      <button class="ui-button">${label}</button>`;
    case "input":
      return `      <input class="ui-input" placeholder="${label}" />`;
    case "text":
      return `      <p class="ui-text">${label}</p>`;
    case "toggle":
      return `      <label class="ui-toggle"><input type="checkbox" /> ${label}</label>`;
    case "image":
      return `      <div class="ui-image">${label}</div>`;
    case "list":
      return `      <ul class="ui-list"><li>${label} item 1</li><li>${label} item 2</li></ul>`;
    case "grid":
      return `      <div class="ui-grid"><span>${label}</span><span>${label}</span></div>`;
    case "container":
    default:
      return `      <div class="ui-container">${label}</div>`;
  }
}

function renderBody(nodes: ExportNode[]): string {
  if (nodes.length === 0) {
    return `      <p class="ui-text">Your app is empty. Add components in SENTINEL.</p>`;
  }
  return nodes.map(renderNode).join("\n");
}

const SHARED_CSS = `* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; background: #0b1220; color: #e6edf6; }
.app { max-width: 760px; margin: 0 auto; padding: 24px; display: flex; flex-direction: column; gap: 14px; }
.app h1 { font-size: 22px; margin: 0 0 8px; }
.ui-button { background: #1f6feb; color: #fff; border: 0; border-radius: 8px; padding: 12px 16px; font-size: 15px; cursor: pointer; }
.ui-input { background: #111a2b; border: 1px solid #243049; color: #e6edf6; border-radius: 8px; padding: 12px; }
.ui-text { margin: 0; color: #b9c4d4; }
.ui-toggle { display: flex; align-items: center; gap: 8px; }
.ui-image { background: #111a2b; border: 1px dashed #243049; border-radius: 8px; padding: 40px; text-align: center; color: #8895a8; }
.ui-list { background: #111a2b; border-radius: 8px; padding: 12px 28px; }
.ui-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
.ui-grid span { background: #111a2b; border-radius: 8px; padding: 24px; text-align: center; }
.ui-container { background: #111a2b; border: 1px solid #243049; border-radius: 8px; padding: 20px; }`;

function appHtml(appName: string, nodes: ExportNode[]): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${esc(appName)}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <main class="app">
      <h1>${esc(appName)}</h1>
${renderBody(nodes)}
    </main>
    <script src="app.js"></script>
  </body>
</html>
`;
}

// ---- Web app (full stack: static front-end + Express API) ----
export function generateWebApp(
  appName: string,
  nodes: ExportNode[],
): Record<string, string> {
  return {
    "package.json": JSON.stringify(
      {
        name: appName.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "sentinel-app",
        version: "1.0.0",
        private: true,
        scripts: { start: "node server.js" },
        dependencies: { express: "^4.19.2" },
      },
      null,
      2,
    ),
    "server.js": `const express = require("express");
const path = require("path");
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

// Example API endpoint — extend with your own logic.
app.get("/api/health", (_req, res) => res.json({ ok: true, app: ${JSON.stringify(
      appName,
    )} }));

app.listen(PORT, () => console.log("Running on http://localhost:" + PORT));
`,
    "public/index.html": appHtml(appName, nodes),
    "public/styles.css": SHARED_CSS,
    "public/app.js": `// Front-end logic for ${appName}
fetch("/api/health").then(r => r.json()).then(d => console.log("API:", d));
document.querySelectorAll(".ui-button").forEach(b =>
  b.addEventListener("click", () => alert(b.textContent + " clicked"))
);
`,
    "README.md": `# ${appName}\n\nFull-stack web app generated by SENTINEL.\n\n## Run\n\n\`\`\`\nnpm install\nnpm start\n\`\`\`\n\nOpen http://localhost:3000\n`,
  };
}

// ---- Android app (Capacitor-style WebView wrapper) ----
export function generateAndroidApp(
  appName: string,
  nodes: ExportNode[],
): Record<string, string> {
  const pkg = "com.sentinel." + (appName.toLowerCase().replace(/[^a-z0-9]/g, "") || "app");
  return {
    "app/src/main/assets/www/index.html": appHtml(appName, nodes),
    "app/src/main/assets/www/styles.css": SHARED_CSS,
    "app/src/main/assets/www/app.js": `document.querySelectorAll(".ui-button").forEach(b =>
  b.addEventListener("click", () => alert(b.textContent + " clicked"))
);
`,
    "app/src/main/AndroidManifest.xml": `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${pkg}">
  <application android:label="${esc(appName)}" android:icon="@mipmap/ic_launcher">
    <activity android:name=".MainActivity" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
  </application>
</manifest>
`,
    [`app/src/main/java/${pkg.replace(/\./g, "/")}/MainActivity.java`]: `package ${pkg};

import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebView;

public class MainActivity extends Activity {
  @Override protected void onCreate(Bundle s) {
    super.onCreate(s);
    WebView web = new WebView(this);
    web.getSettings().setJavaScriptEnabled(true);
    web.loadUrl("file:///android_asset/www/index.html");
    setContentView(web);
  }
}
`,
    "build.gradle": `// Android Gradle build for ${appName}
plugins { id 'com.android.application' }
android {
  namespace '${pkg}'
  compileSdk 34
  defaultConfig {
    applicationId '${pkg}'
    minSdk 24
    targetSdk 34
    versionCode 1
    versionName '1.0'
  }
}
`,
    "README.md": `# ${appName} (Android)\n\nAndroid WebView app generated by SENTINEL.\nOpen this folder in Android Studio and press Run.\n`,
  };
}
